name: 超哥的个人网站
description: 超哥在这里分享他的观点和各种兴趣爱好，以及他平时搜集整理的各种笔记
markdown: redcarpet
pygments: true
exclude:
  - vendor
  - bin
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - Rakefile
  - nginx.conf
  - favicon.psd
  - favicon.png
  - farr-better-icecream-big.jpg
encoding: UTF-8
